### ISSUE TITLE
use `replace` instead of parser

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/action-s3cp#1]
instead of using our own parser, we could just get away with using `String.replace`

```
function resolvePath(path){
  let newPath = path.replace(/{branch}/g, getCurrentBranchName(cwd)+"/")
  newPath = newPath.replace(any other rule we might have)
  ...
  return newPath
}

```
https://github.com/kaskadi/action-s3cp/blob/d6d52f078ceb926e9cf994772acb653180a0676e/index.js#L28

**Comment by alexlemaire** [comment]
Done, closing
