### ISSUE TITLE
is there a way to unit test actions?

### ISSUE THREAD

**Issue by Holger-Will** [kaskadi/action-s3cp#3]

**Comment by alexlemaire** [comment]
I will have a look at this. Duplicating this issue for `action-slscli` repo.

**Comment by alexlemaire** [comment]
See [here](https://github.com/kaskadi/template-action/issues/1) for tracking

**Comment by alexlemaire** [comment]
Closing for now. See previous comment. Working on [template level](https://github.com/kaskadi/template-action) and will dispatch solution into each action.
